rat=imread("rat1.jpg");
rat_gray=im2double(rgb2gray(rat));
c=1;
g=0.4;
rat_gray_new_1=im2double(c.*rat_gray.^g);
c=1;
g=1;
rat_gray_new_2=im2double(c.*rat_gray.^g);
c=1;
g=2.5;
rat_gray_new_3=im2double(c.*rat_gray.^g);
subplot(4, 2, 1);
imshow(rat_gray);
title('original');
subplot(4, 2, 2);
imhist(rat_gray);
subplot(4, 2, 3);
imshow(rat_gray_new_1);
title('gamma=0.4');
subplot(4, 2, 4);
imhist(rat_gray_new_1);
subplot(4, 2, 5);
imshow(rat_gray_new_2);
title('gamma=1');
subplot(4, 2, 6);
imhist(rat_gray_new_2);
subplot(4, 2, 7);
imshow(rat_gray_new_3);
title('gamma=2.5');
subplot(4, 2, 8);
imhist(rat_gray_new_3);